---
name: Devel
on:
  push:
    branches: [devel]
jobs:
  release:
    runs-on: ARM64
    name: Push devel image
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          IMG=awx-operator:devel BUILD_ARGS='--platform linux/arm64' make docker-build
      - name: Login to registry
        run: |
          sudo docker login ${{ secrets.REGISTRY_URL }} --username ${{ secrets.REGISTRY_USER }} --password  ${{ secrets.REGISTRY_PASS }}

      - name: Push image to registry
        run: |
          sudo docker image push harbor.cws.land/ansible/awx-operator:devel

