---
name: Devel
on:
  push:
    branches: [devel]
jobs:
  release:
    runs-on: ARM64
    name: Push devel image
    steps:
      - uses: actions/checkout@v2
      - name: Build Image
        run: |
          IMG=awx-operator:devel BUILD_ARGS='--platform linux/arm64' make docker-build
      - name: install podmanm
        run: |
          sudo apt-get -y install podman
      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: awx-operator
          tags: devel
          registry: harbor.cws.land/ansible/
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

